### ISSUE TITLE
Use opencv's houghCircle instead of fresh code.

### ISSUE THREAD

**Issue by tejus-gupta** [SithAP/obstacle_removal#1]
Wouldn't opencv's feature detectors be pretty optimized in terms on performance? 
Check http://docs.opencv.org/2.4/doc/tutorials/imgproc/imgtrans/hough_circle/hough_circle.html

**Comment by APS-Arora** [comment]
They obviously are optimised but they cannot be used here because hough circle function in opencv applies Canny Edge Detection before applying Hough Circle Transform. This is helpful only when the points are continuous which is not our case. If you can find any function in opencv that only applies hough transform directly, I'll replace the code with that.
